receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  cumulativetodelta:
    max_staleness: 25h

exporters:
  otlp_http:
    metrics_endpoint: "${env:DT_ENDPOINT}/v1/metrics"
    traces_endpoint: "${env:DT_ENDPOINT}/v1/traces"
    logs_endpoint: "${env:DT_ENDPOINT}/v1/logs?structure=flattened"
    headers:
      Authorization: "Api-Token ${env:DT_API_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp_http]
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta]
      exporters: [otlp_http]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlp_http]